### PR TITLE
bump version to 2.0.2

### PR DESCRIPTION
**Pull request by kmahyyg**

### CODE REVIEW

**Comment by kmahyyg** [comment]
Tested on my own machine.

**Comment by yiranzai** [comment]
我正要这么做。
good job

**Comment by kmahyyg** [comment]
If the owner doesn't merge this PR in a week, I'm gonna make a new PKG called `picgo2-appimage` by myself.

**Comment by yiranzai** [comment]
@kmahyyg  我制作了包但是没有发布，我自己用了

**Comment by houbaron** [comment]
@kmahyyg 谢谢！

**Pull request merged**
